# Generated by Django 2.2.6 on 2019-12-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='jokers',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='removed_cards',
        ),
        migrations.AddField(
            model_name='deck',
            name='card_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='current_card',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='hand',
            name='cards',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
